### ISSUE TITLE
Some text on es wiki is hard to read

### ISSUE THREAD

**Issue by theslimshaney** [StylishThemes/Wikipedia-Dark#111]
The text near the top right under the search bar is hard to read
https://es.wikipedia.org/wiki/Wikipedia:Portada
![image](https://user-images.githubusercontent.com/33791263/73146605-6300e180-4068-11ea-9b2a-44d64eed0a8a.png)

Not sure how to fix it, but the color is set here
https://github.com/StylishThemes/Wikipedia-Dark/blob/0d74fbf3e8885b1bc3df6566d4f55931c8ddaa1c/wikipedia-dark.user.css#L2048-L2053

**Comment by AfroThundr3007730** [comment]
I think a [hack](https://github.com/StylishThemes/Wikipedia-Dark/blob/2268f41b5955ba525d4503db4bcaea45d1c60c98/wikipedia-dark.user.css#L4722) similar to what we did on ruwiki's [main page](https://ru.wikipedia.org/wiki/Main_Page) might be in order here:
```css
.mw-parser-output .main-top-right {
    background-image: linear-gradient(to left, var(--gray-3_5) 30%, transparent 60%);
}
```
@the-j0k3r What do you think?
