### ISSUE TITLE
Main page on enwiki was rewritten (styles broken now)

### ISSUE THREAD

**Issue by AfroThundr3007730** [StylishThemes/Wikipedia-Dark#112]
After a [technical update](https://en.wikipedia.org/wiki/Special:Diff/939200667) to the main page on enwiki, none of the styles targeting that page are working anymore (this affects mobile too). For background, you can see the related discussion [here](https://en.wikipedia.org/w/index.php?oldid=939240484#Main_Page_January_2020_technical_update).

The good news is, the page was rewritten to take advantage of [TemplateStyles](https://www.mediawiki.org/wiki/Extension:TemplateStyles), which means everything is now using CSS classes instead of inline styles, so no more `!important` spamming needed.

I don't have the time to tackle this right now, hence the bug. :stuck_out_tongue:

**Comment by the-j0k3r** [comment]
Great, spend a million hours fixing this style and now its bombed. Great news indeed!

**Comment by AfroThundr3007730** [comment]
I know that feel. At least it's limited to one page - for now, they're eyeballing the other project main pages as well if all goes well on enwiki. The classes should make this easier to fix though.

**Comment by the-j0k3r** [comment]
Its a ess, whos gonna know which old hack belong here to remove it? I mean the sane thing to do is just re-style it and then you leave a ton of trash behind.

Again, this really needs a generator and a new style. One page here one page there and theres go any time I have for other jobs, + I dont really use this style.

I dont think I have the patience otherwise to tackle this without a generator. I think the old proverbial straw and Camels back comes to mind.

**Comment by AfroThundr3007730** [comment]
Is the style generator ready for general use yet, or is there still work to be done? I'm all for making this style easier to maintain, and the GH-Dark style seems to be doing great using it.

**Comment by the-j0k3r** [comment]
style generator is far away from being ready to be easily transplanted to other sites @silverwind is the only gut that knows about it enough to get to it, an its like everything, it needs time and patience to do also.

We lost @Mottie to real life so without more active devs who know JS at that level to handle the generator, the pipe dream continues.
>The good news is, the page was rewritten to take advantage of TemplateStyles, which means everything is now using CSS classes instead of inline styles, so no more !important spamming needed.

That would be true with a new style, being this ol thing, you still unfortunately need to break more CSS with !important even in these new classes.

**Comment by the-j0k3r** [comment]
Good news: fix more or less incoming.

Bad news: I wont be fixing the mobile pages period! so whoever is interested in that can go for it.

**Comment by AfroThundr3007730** [comment]
> Bad news: I wont be fixing the mobile pages period! so whoever is interested in that can go for it.

By the power of the new classes, we need but apply your new rules as-is to the mobile block:
```css
  .mw-parser-output .MainPage__column--left {
    border: 1px solid var(--green-1);
    color: var(--gray-e);
    background-color: var(--green-4);
  }
  .mw-parser-output .MainPage__heading--featured-article,
  .mw-parser-output .MainPage__heading-dyk {
    background: var(--green-2);
    border: 1px solid var(--green-1);
    color: var(--gray-c);
  }
  h2[style*="color:white;"] {
    color: var(--gray-e);
  }
  .mw-parser-output .MainPage__banner {
    border: 1px solid var(--gray-4);
    background-color: var(--gray-28);
    color: var(--gray-e);
  }
  .mw-parser-output .MainPage__heading--other,
  .mw-parser-output .MainPage__heading--sister,
  .mw-parser-output .MainPage__heading--languages {
    border: 1px solid var(--gray-5);
    background-color: var(--gray-3);
    color: var(--gray-c);
  }
  .mw-parser-output .MainPage__column--right {
    border: 1px solid var(--blue-4);
    background: var(--blue-2);
  }
  .mw-parser-output .MainPage__heading--itn,
  .mw-parser-output .MainPage__heading--otd {
    background: var(--blue-4);
    border: 1px solid var(--blue-1);
    color: var(--gray-c);
  }
  .mw-parser-output .MainPageBG--featured-picture {
    background: var(--purple-d);
    border-color: var(--purple-2);
  }
  .mw-parser-output .MainPage__heading--featured-picture {
    background: var(--purple-1);
    border: 1px solid var(--purple-2);
    color: var(--gray-c);
  }
```

I'll push this in a sec.
