### ISSUE TITLE
More Wikipedia home page weirdness (and something on Wikiquote)

### ISSUE THREAD

**Issue by kfdz277** [StylishThemes/Wikipedia-Dark#128]
* **Browser**: Firefox 76.0.1
* **Operating System**: Windows 10 1909
* **Link to page with the issue**: https://en.wikipedia.org/wiki/Main_Page
* **Screenshot**: 
![image](https://user-images.githubusercontent.com/55974345/82716460-8d089000-9c65-11ea-9c5a-b114fe28e528.png)

feel free to quote this part out of context into a different issue because i cant tell whether it should or should not be here... there's also some weirdness on wikiquote, https://en.wikiquote.org/wiki/John_Steinbeck#The_Grapes_of_Wrath_(1939) . the disputed quotes section 
![image](https://user-images.githubusercontent.com/55974345/82716610-4ebfa080-9c66-11ea-8bda-6fa8e0ddd2e4.png)

**Comment by timsj** [comment]
I'm having the same issue on the Wikipedia main page. The article pages themselves seem fine. Firefox 76.0.1, macOS 10.15.4

**Comment by AfroThundr3007730** [comment]
Ugh, I wish they'd settle on a design for the responsive style..

They keep renaming the classes and IDs, but here are the restored colors:

```css
.mw-parser-output #mp-topbanner {
    /* border-color: #ddd; */
    /* background-color: #f9f9f9; */
    border-color: var(--gray-5);
    background-color: var(--gray-2);
}
.mw-parser-output #mp-topbanner, .mw-parser-output .mp-h2, .mw-parser-output #mp-left {
    /* color: #000; */
    color: var(--gray-c);
}
.mw-parser-output #mp-right {
    /* border-color: #cedff2; */
    /* background: #f5faff; */
    border-color: var(--blue-1);
    background: var(--blue-2);
}
.mw-parser-output #mp-right .mp-h2 {
    /* border-color: #a3b0bf; */
    border-color: var(--blue-1);
}
.mw-parser-output #mp-left {
    /* border-color: #cef2e0; */
    /* background: #f5fffa; */
    border-color: var(--green-1);
    background: var(--green-4);
}
.mw-parser-output #mp-left .mp-h2 {
    /* border-color: #a3bfb1; */
    border-color: var(--green-1);
}
.mw-parser-output #mp-middle {
    /* border-color: #f2cedd; */
    /* background: #fff5fa; */
    border-color: var(--pink-2);
    background: var(--pink-0);
}
.mw-parser-output #mp-tfl-h2 {
    /* border-color: #bfa3af; */
    border-color: var(--pink-2);
}
.mw-parser-output #mp-lower {
    /* border-color: #ddcef2; */
    /* background: #faf5ff; */
    border-color: var(--purple-2);
    background: var(--purple-d);
}
.mw-parser-output #mp-tfp-h2 {
    /* border-color: #afa3bf; */
    border-color: var(--purple-2);
}
.mw-parser-output #mp-other-lower {
    /* border-color: #e2e2e2; */
    border-color: var(--gray-5);
}
.mw-parser-output #mp-other-lower .mp-h2 {
    /* background: #eee; */
    /* border-color: #ddd; */
    background: var(--gray-28);
    border-color: var(--gray-5);
}
```

Sorry I don't have time to fix these right now. Might add em later or something.

Also note that the main page styles now live at [Wikipedia:Main Page/styles.css](https://en.wikipedia.org/wiki/Wikipedia:Main_Page/styles.css) for reference.
