### ISSUE TITLE
Mimi Pink becoms --brown-1

### ISSUE THREAD

**Issue by JohnSmith777779** [StylishThemes/Wikipedia-Dark#176]
* **Browser**: Google Chrome 90.0.4430.93 (Official Build) (64-bit), Microsoft Edge 90.0.818.49 (Official build) (64-bit)
* **Operating System**: Windows 10 OS Version 1809 (Build 17763.973)
* **Link to page with the issue**: https://en.wikipedia.org/wiki/Template:Shades_of_pink
* **Screenshot**: 
![image](https://user-images.githubusercontent.com/68935009/116570620-696bb200-a8d8-11eb-93a3-d33ae2a915fd.png)

**Comment by JohnSmith777779** [comment]
So it turns out that the box has the style **`background:#FFD`**`AE9;border:1px solid;`, and the code

```css
  .table-partial, tr[style*="background:orange" i],
  td[style*="background:#ffd" i] {
    background-color: var(--brown-1) !important;
  }
```
makes it brown.

**Comment by JohnSmith777779** [comment]
This is the template with the above piece of code removed (which might be breaking something else)

![image](https://user-images.githubusercontent.com/68935009/116573016-725d8300-a8da-11eb-8e60-b6a8225b45cf.png)

**Comment by JohnSmith777779** [comment]
I just "fixed" it for myself by appending
```css
td[style*="background:#FFDAE9"] {
    background: #FFDAE9 !important;
}
```
(probably don't do this for every possible color that could be affected, this is very minor anyway)
