### ISSUE TITLE
links aren't distinguishable from normal text

### ISSUE THREAD

**Issue by atticusmatticus** [StylishThemes/Wikipedia-Dark#49]
The color of the link text in Wikipedia-Dark is the same as normal non-link text. When the cursor is over the link text it becomes a brighter white color and gets and underline which is nice but it would be more useful to be able to see what is a link and what is just normal text without having to drag the cursor over all the text.

Thanks

**Comment by atticusmatticus** [comment]
Thanks for the reply. What is that screenshot from? I’m using Cascadea on macOS and I’ve never seen that.

**Comment by Mottie** [comment]
That's a screenshot of [Stylus](https://add0n.com/stylus.html) which isn't available for Safari, but does support most other browsers.

I don't know how Cascadea works, but if it allows you to add custom css, then copy/paste this block of css and replace the colors and target the same wikipedia domains, it will override the default Wikipedia-Dark settings ([ref](https://github.com/StylishThemes/Wikipedia-Dark/blob/master/wikipedia-dark.user.css#L45-L52)):

```css
:root {
  --base-color: #4183C4;
  --base-color-8: rgba(65, 131, 196, .8);
  --visited-color: #295887;
  --bg-selected: url("");
  --bg-attachment: scroll;
}
```

You can ignore the `--bg-custom` variable.
