### ISSUE TITLE
Width wrapping

### ISSUE THREAD

**Issue by qlonik** [StylishThemes/Wikipedia-Dark#51]
Could you add an option to be able to wrap the text on the page based on some width value (900px or something like this)?

**Comment by Mottie** [comment]
Hi @qlonik!

How about I let you test this usercss style for me. Hopefully you're using [Stylus](https://add0n.com/stylus.html). If so:

* [Open the manager](https://github.com/openstyles/stylus/wiki/Manager#opening-the-manager) and check the "as Usercss" checkbox
* Then click the ["Write new style"](https://github.com/openstyles/stylus/wiki/Manager#write-new-style) button next to it.
* Select all content (<kbd>Ctrl</kbd> + <kbd>a</kbd>) in the editor.
* And finally paste (<kbd>Ctrl</kbd> + <kbd>v</kbd>) in the following css:

```css
/* ==UserStyle==
@name           Wikipedia width
@namespace      StylishThemes
@version        1.0.0
@description    Fix the width of wikipedia body
@author         StylishThemes
@var number width "Width" [900, "px"]
==/UserStyle== */

@-moz-document domain("wikipedia.org") {
  body {
    max-width: var(--width);
    margin: 0 auto;
  }
  #mw-panel {
    left: calc(50% - var(--width) / 2);
  }
  #left-navigation {
    margin-left: calc(50% - var(--width) * .305);
  }
}
```

Now in the [popup](https://github.com/openstyles/stylus/wiki/Popup), use the [usercss config](https://github.com/openstyles/stylus/wiki/Popup#interface) to modify the default setting of `900px` to any value you want.

If this works well for you, you can either keep it as a separate style or I'll integrate it into the main dark style once it's been tested and refined.

**Comment by qlonik** [comment]
Hello, sorry it took me some time to get back.

It works pretty well. I've taken couple screenshots.
It resizes everything well and moves all the content into the center.

The only weird thing is that top buttons (main page/talk/read/source) and search bar are behaving funny. Also, some nitpicking details is that after resizing like this, I can pretty clearly see outline of the main page box on the left and right of the text - they are very faint light gray and black vertical lines. These lines also disappear after I scroll past the first page, which is weird.
Ahh, this line is because background of main text and the rest of page is not aligning completely, so two gray boxes are touching each other on one side, and on another side there is a gap that is too wide.

![disabled_extension_3840x2160](https://user-images.githubusercontent.com/1373271/49481416-dd352d80-f7f8-11e8-89c3-3fad90b7963b.png)
![900px_width_3840x2160](https://user-images.githubusercontent.com/1373271/49481422-ec1be000-f7f8-11e8-9983-a56fa551f6a7.png)
![1280px_width_3840x2160](https://user-images.githubusercontent.com/1373271/49481431-f63dde80-f7f8-11e8-8eec-3ed01e661b7f.png)

**Comment by Mottie** [comment]
I updated the css in my first post to include the `#right-navigation`.

**Comment by qlonik** [comment]
Sorry, I forgot about it.
I tried playing around with css a little bit and came up with the following, which seems to be working very well. I also enabled text to be, so it is easier to read.

```css
/* ==UserStyle==
@name           Wikipedia width
@namespace      StylishThemes
@version        1.0.0
@description    Fix the width of wikipedia body
@author         StylishThemes
@var number width "Width" [900, "px"]
==/UserStyle== */

@-moz-document domain("wikipedia.org") {
  body {
    max-width: var(--width);
    margin: 0 auto;
  }
  #mw-head {
    max-width: var(--width);
    right: inherit;
  }
  #mw-panel {
    left: inherit;
  }
  #mw-content-text p {
    text-align: justify;
  }
}
```
