### ISSUE TITLE
White headbar in English Wikipedia

### ISSUE THREAD

**Issue by TotalCaesar659** [StylishThemes/Wikipedia-Dark#93]
https://en.wikipedia.org/wiki/Xubuntu
![1](https://user-images.githubusercontent.com/14265316/67697398-82309a00-f9b9-11e9-8592-b6535ac81dd5.png)

**Comment by Mottie** [comment]
Actually that is an svg with a white background behind it:

```css
a.image img, a[href*=".svg"] img {
  background: var(--gray-d) !important;
}
```

We did that to make transparent images with dark text more visible. Maybe we can add an exception for svgs in the `.infobox`.
