### ISSUE TITLE
white http://stylishthemes.github.io/Wikipedia-Dark/

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/Wikipedia-Dark#95]
* **Browser**: Firefox 73.0.1
* **Operating System**: Win
* **Link to page with the issue**: http://stylishthemes.github.io/Wikipedia-Dark/ 
* **Screenshot**:
![Screenshot_2019-11-04 Wikipedia-Dark](https://user-images.githubusercontent.com/31389848/68144736-8ff39b80-ff34-11e9-9dd7-8f0ea065db29.png)

**Comment by the-j0k3r** [comment]
ugh should have reported this against Github Dark

**Comment by the-j0k3r** [comment]
Can be fixed with adding `domain("github.io")` to Github Dark

**Comment by the-j0k3r** [comment]
```css
@-moz-document domain("github.io") {
  :root {
    --bg-custom: /*[[bg-custom]]*/;
    --bg-img: /*[[bg-choice]]*/;
  }
  * {
	  box-sizing: border-box;
  }
  body {
    color: #e0e0e0;
    background-color: #222;
    background-image: var(--bg-img);
    background-clip: border-box;
    background-origin: padding-box;
    background-attachment: /*[[bg-attachment]]*/;
    /*[[bg-options]]*/
  }
	.markdown-body img {
		background-color: #181818;
		background: none;
	}
  a {
	  color: /*[[base-color]]*/;
		background-color: transparent;
  }
  .markdown-body h1, .markdown-body h2, .markdown-body h3,
	.markdown-body h4, .markdown-body h5, .markdown-body h6 {
	  border-bottom: 1px solid #444;
  }
	.border-gray-light {
	  border-color: #444 !important;
  }
	.markdown-body table th, .markdown-body table td {
	  border: 1px solid #444;
  }
	.text-gray {
	  color: #aaa !important;
  }
	.markdown-body table tr {
	  background-color: #181818;
	  border-top: 1px solid #444;
  }
	.markdown-body table tr:nth-child(2n) {
    background-color: #202020;
  }
}
```

That section fixes it in GitHub Dark but I wonder if ters a reason why we dont style these already, like perhaps it would affect all github pages hosted sites too?
It can be restricted to the affected internal stylishthemes URL's also and only.
